# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-10 19:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaBloom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name=b'Nombre')),
                ('seq', models.IntegerField(verbose_name=b'Secuencia')),
            ],
        ),
        migrations.CreateModel(
            name='CategoriaBloomValor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name=b'Nombre')),
                ('categ_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.CategoriaBloom')),
            ],
        ),
    ]
