# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-10 19:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_categoriabloom_categoriabloomvalor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoriabloom',
            options={'verbose_name': 'Categoria Bloom', 'verbose_name_plural': 'Categorias Bloom'},
        ),
        migrations.AlterModelOptions(
            name='categoriabloomvalor',
            options={'verbose_name': 'Valor categoria Bloom', 'verbose_name_plural': 'Valores categorias Bloom'},
        ),
    ]
