# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-14 18:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20160605_1812'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultadoaprendizaje',
            name='asig_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='core.Asignatura'),
        ),
    ]
